### ISSUE TITLE
WatchKit apps cannot be dumped

### ISSUE THREAD

**Issue by Tatsh** [KJCracks/Clutch#81]
Twitter v6.24.4

```
2015-03-28 20:40:42.133 clutch[63761:3947502] Failed to crack plugin: Twitter WatchKit Extension with error: Error Domain=BinaryDumpError Code=-1 "Cannot crack unswapped %@ portion of binary." UserInfo=0x15017f5e0 {NSLocalizedDescription=Cannot crack unswapped %@ portion of binary.}
```

Is this fixed in a later version or in 2.0?

**Comment by Tatsh** [comment]
Not sure if #79 and #73 are related to this, but it seems like it.

**Comment by ttwj** [comment]
this should've been fixed in Clutch 2

**Comment by Tatsh** [comment]
Not fixed, unless you mean it works under iOS 8.3. I think the reason this occurs is because there's no way to 'run' the WatchKit app part of this under iOS 8.1.1.

Also, #73 is not fixed either and I think it is the same reason.

I am using the public beta 2.0.
